let data = [
    {
      _id: 1,
      title: "Men Tshirt",
      subdescription: "high quality 100% cotton tshirt men , custom plain blank summer tshirts",
      description:
        "100% mricfiber polyester twill fabric are soft and comfortable feeling，breathable and no pilling,natural and healthy.",
      price: "14",
      slug: "MenTshirt",
      image: "/images/1.jpeg",
      numberofrating: "510",
      model: "M",
      rating: "4.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 2,
      title: "tshirt men",
      subdescription: "high quality 100% cotton tshirt men , custom plain blank summer tshirts",
      description: "high quality 100% cotton tshirt men , custom plain blank summer tshirts ,wholesale tshirt in China 1pc into 1 poly bag.",
      price: "10",
      slug: "tshirtmen",
      image: "/images/2.jpeg",
      numberofrating: "347",
      model: "L",
      rating: "5",
      cupon: "May13Friday22",
      instock: 15,
    },
    {
      _id: 3,
      title: "cotton pullover",
      subdescription: "high quality 100% cotton tshirt men , custom plain blank summer tshirts",
      description:
        "Cuastom heavy fleece hoodie. Our hoodies are not only heavy, our fabrics are delicate, soft and delicate. Selection of active dye not fade.",
      price: "23",
      slug: "cottonpullover",
      image: "/images/3.jpeg",
      numberofrating: "156",
      model: "L",
      rating: "3.5",
      cupon: "May13Friday22",
      instock: 0,
    },
    {
      _id: 4,
      title: "leisure",
      subdescription: "Sports suit men's summer leisure suit gym clothes plablank summert shirts",
      description:
        "Sports suit men's summer leisure suit gym clothes loose round collar group custom speed dry clothing T-shirt",
      price: "16",
      slug: "leisure",
      image: "/images/4.jpeg",
      numberofrating: "206",
      model: "M",
      rating: "4",
      cupon: "May13Friday22",
      instock: 5,
    },
    {
      _id: 5,
      title: "Korean Jacket",
      subdescription: "high quality 100% cotton tshirt men , custom plain blank summer tshirts",
      description:
        "Spring Autumn 2021 Casual Streetwear Men's Korean Trendy Jacket Youth Slim Handsome Clothes Men's Black Denim Jacket",
      price: "15",
      slug: "KoreanJacket",
      image: "/images/5.jpeg",
      numberofrating: "86",
      model: "XL",
      rating: "4.5",
      cupon: "May13Friday22",
      instock: 10,
    },
    {
      _id: 6,
      title: "Polo Shirts",
      subdescription: "high quality 100% cotton tshirt men , custom plain blank summer tshirts",
      description:
        "Long Sleeves Polo Shirts OEM High Quality Custom Sports Polo T-Shirt Men's Polo Shirts Custom Logo Printed Men Clothes FSW-4017",
      price: "15",
      slug: "PoloShirts",
      image: "/images/6.jpeg",
      numberofrating: "186",
      model: "XL",
      rating: "2.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 7,
      title: "Fit Blazer",
      subdescription: "high quality 100% cotton tshirt men , custom plain blank summer tshirts",
      description:
        "Spring Clothes Men Fashion Tops Slim Fit Blazer Casual Solid Color Male Suits Corduroy Single Button Unique Long Sleeve Jackets",
      price: "25",
      slug: "FitBlazer",
      image: "/images/7.jpeg",
      numberofrating: "356",
      model: "M",
      rating: "4.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 8,
      title: "windbreaker",
      subdescription: "Men pullover bulk windbreaker anorak hooded jacket",
      description:
        "Men pullover bulk windbreaker anorak hooded jacket winter wears men's jacket turkey",
      price: "17",
      slug: "windbreaker",
      image: "/images/8.jpeg",
      numberofrating: "56",
      model: "XL",
      rating: "3.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 9,
      title: "sports T-shirt",
      subdescription: "high quality 100% cotton tshirt men , custom plain blank summer tshirts",
      description:
        "The latest new type of fitness clothes men's slim sports T-shirt breathable men's T-shirt",
      price: "15",
      slug: "sportsT-shirt",
      image: "/images/9.jpeg",
      numberofrating: "560",
      model: "M",
      rating: "4.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 10,
      title: "Hoodie",
      subdescription:
        "Sun Protection Hoodie Shirt Long Sleeve SPF Fishing Outdoor",
      description:
        "Willit Men's UPF 50+ Sun Protection Hoodie Shirt Long Sleeve SPF Fishing Outdoor UV Shirt Hiking Lightweight",
      price: "35",
      slug: "Hoodie",
      image: "/images/10.jpeg",
      numberofrating: "460",
      model: "S",
      rating: "4.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 11,
      title: "jeans",
      subdescription: "New tattered cat whiskers men slim wash jeans black print",
      description:
        "New tattered cat whiskers men slim wash jeans black print skinny stretch men's pants men's jeans",
      price: "26",
      slug: "washjeans",
      image: "/images/11.jpeg",
      numberofrating: "421",
      model: "L",
      rating: "3.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 12,
      title: "Pullover Hoodie",
      subdescription:
        "Champion Men's Powerblend Fleece Pullover Hoodie, Script Logo",
      description:
        "Champion Men's Powerblend Fleece Pullover Hoodie, Script Logo",
      price: "23",
      slug: "PulloverHoodie",
      image: "/images/12.jpeg",
      numberofrating: "31",
      model: "M",
      rating: "4.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 13,
      title: "Coat",
      subdescription: "sandbank Men's Slim Fit Lightweight Bomber Jacket Coat",
      description:
        "sandbank Men's Slim Fit Lightweight Softshell Flight Bomber Jacket Coat",
      price: "35",
      slug: "Coat",
      image: "/images/13.jpeg",
      numberofrating: "310",
      model: "S",
      rating: "4.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 14,
      title: "Jersey Tee",
      subdescription: "Champion Men's Classic Jersey Tee",
      description:
        "Champion Men's Classic Jersey Tee 100% Cotton; Oxford Grey: 90% Cotton, 10% Polyester; Heather: 50% Cotton, 50% Polyester",
      price: "35",
      slug: "Jersey Tee",
      image: "/images/14.jpeg",
      numberofrating: "324",
      model: "M",
      rating: "5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 15,
      title: "Hunting Jacket",
      subdescription: "Sitka Men's Celsius Midi Insulated Hunting Jacket",
      description:
        "Sitka Men's Celsius Midi Insulated Hunting Jacket PrimaLoft Silver hi-loft insulation that is virtually silent, quick drying and warm even if you get it wet",
      price: "27",
      slug: "Hunting Jacket",
      image: "/images/15.jpeg",
      numberofrating: "220",
      model: "XL",
      rating: "2.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 16,
      title: "Shirt Jacket",
      subdescription: "Men's Long Sleeve Quilted Lined Flannel Shirt Jacket",
      description:
        "Wrangler Authentics Men's Long Sleeve Quilted Lined Flannel Shirt Jacket with Hood",
      price: "31",
      slug: "ShirtJacket",
      image: "/images/16.jpeg",
      numberofrating: "175",
      model: "M",
      rating: "1.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 17,
      title: "Henley Tee",
      subdescription: "Wrangler Authentics Men's Short Sleeve Henley Tee",
      description:
        "Tech fabric is quick-drying, ultra-soft & has a more natural feel",
      price: "29",
      slug: "Henley Tee",
      image: "/images/17.jpeg",
      numberofrating: "321",
      model: "M",
      rating: "3.5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 18,
      title: "Jacket",
      subdescription: "high quality 100% cotton tshirt men , custom plain blank summer tshirts",
      description:
        "Champion Stadium Packable Jacket, Lightweight Water and Wind Resistant Pullover, Half Zip Hooded Windbreaker",
      price: "18",
      slug: "Jacket",
      image: "/images/18.jpeg",
      numberofrating: "144",
      model: "L",
      rating: "4",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 19,
      title: "Windrunner Jacket",
      subdescription: "Nike mens Men Nike Windrunner Jacket",
      description: "Nike mens Men Nike Windrunner Jacket",
      price: "99",
      slug: "Windrunner Jacket",
      image: "/images/19.jpeg",
      numberofrating: "20",
      model: "M",
      rating: "5",
      cupon: "May13Friday22",
      instock: 11,
    },
    {
      _id: 20,
      title: "Hooded Sweatshirt",
      subdescription: "Hanes Men's Pullover EcoSmart Hooded Sweatshirt",
      description: "Hanes Men's Pullover EcoSmart Hooded Sweatshirt",
      price: "11",
      slug: "Hooded Sweatshirt",
      image: "/images/20.jpeg",
      numberofrating: "83",
      model: "XL",
      rating: "2.5",
      cupon: "May13Friday22",
      instock: 11,
    },
]

  export default data